apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "test-urukube-app.fullname" . }}-html
  labels:
    {{- include "test-urukube-app.labels" . | nindent 4 }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head><title>{{ .Values.html.title }}</title></head>
      <body>
        <h1>{{ .Values.html.title }}</h1>
        <p>{{ .Values.html.message }}</p>
      </body>
    </html>
